name: icon_app
description: "Icon Project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  http: ^1.2.1

  flutter_secure_storage: ^9.2.4
  flutter_tts: ^4.2.3
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  logger: ^2.6.1
  speech_to_text: ^7.2.0
  permission_handler: ^12.0.1
  supabase_flutter: ^2.9.1
  webview_flutter: ^4.7.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  share_plus: ^7.2.1
  app_links: ^6.4.0
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/
    - assets/images/